### ISSUE TITLE
Allow use of Linux::Smaps::Tiny as alternative for Linux::Smaps

### ISSUE THREAD

**Issue by timbunce** [audreyt/process-sizelimit-core#3]
Process::SizeLimit::Core tries to load Linux::Smaps and will use it if it loads.
Sadly Linux::Smaps hasn't been updated since 2013 and [doesn't work on RHEL7/CentOS7](https://rt.cpan.org/Public/Bug/Display.html?id=102687).
An alternative version, [Linux::Smaps::Tiny](https://metacpan.org/pod/Linux::Smaps::Tiny), does work on RHEL7/CentOS7.

It would be good if Process::SizeLimit::Core could support either. I presume the change would be fairly simple.

If you're agreeable I'd be happy to work on a PR for this.

**Comment by audreyt** [comment]
Sure! Looking forward to the PR. :rainbow:

**Comment by timbunce** [comment]
This was fixed by #4 but I forgot to close it.
